### ISSUE TITLE
Traveler misbehaving

### ISSUE THREAD

**Issue by stevenrbrandt** [hdc-arizona/traveler-integrated#45]
See screenshot
<img width="920" alt="trav" src="https://user-images.githubusercontent.com/1386187/79365989-0992ab00-7f11-11ea-8dbb-dee977c97367.PNG">

Note the spinner in utilization does not stop.

**Comment by alex-r-bigelow** [comment]
Thanks for filing the issue! Is there anything on the console?

**Comment by stevenrbrandt** [comment]
```
:8000/favicon.ico:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8000/datasets/fib(19)%40184d36e9-31ef-42f8-971a-a70819ab586f-007/histogram?mode=utilization&bins=512:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
d3.min.js:2 Uncaught (in promise) TypeError: Array.prototype.map called on null or undefined
    at map (<anonymous>)
    at Function.l.domain (d3.min.js:2)
    at GanttView.setup (GanttView.js:78)
    at GanttView.render (uki.esm.js:171)
    at GanttView.loadResources (uki.esm.js:155)
d3.min.js:2 Error: <rect> attribute width: A negative value is not valid. ("-30")
(anonymous) @ d3.min.js:2
d3.min.js:2 Uncaught TypeError: Array.prototype.map called on null or undefined
    at map (<anonymous>)
    at Function.l.domain (d3.min.js:2)
    at GanttView.setup (GanttView.js:78)
    at GanttView.render (uki.esm.js:171)
    at Object.<anonymous> (GoldenLayoutView.js:37)
    at e.container.ItemContainer.emit (goldenlayout.min.js:1)
    at e.container.ItemContainer._$setSize (goldenlayout.min.js:1)
    at e.items.Component.setSize (goldenlayout.min.js:2)
    at e.items.Component.callDownwards (goldenlayout.min.js:2)
    at e.items.Stack.callDownwards (goldenlayout.min.js:2)
```

**Comment by alex-r-bigelow** [comment]
Hmm, shoot. 500 means there should be a spew on the command line... Any hints to reproduce? (i.e. was this running `remote_test.py` from JetLag? Running from Jupyter?)

**Comment by stevenrbrandt** [comment]
Yes, this is running remote_test.py from jupyter. Unfortunately, Rostam has decided it won't run phylanx + mpi anymore. You'll need to use the "shelob-sbrandt" for the jetlag_id field.

**Comment by stevenrbrandt** [comment]
Output of serve.py
```
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 100, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 73, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 62, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 585, in __call__
    await route(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 207, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 43, in app
    await response(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/responses.py", line 197, in __call__
    async for chunk in self.body_iterator:
  File "/traveler-integrated/data_store/loggers.py", line 17, in iterate
    await startProcess()
  File "serve.py", line 168, in startProcess
    await db.processOtf2(label, FakeOtf2File(request), storeEvents, logger.log)
  File "/traveler-integrated/data_store/_otf2Functions.py", line 141, in processOtf2
    assert currentEvent is not None and addAttrLineMatch is not None
AssertionError

```

**Comment by stevenrbrandt** [comment]
also
```
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 73, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 62, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 585, in __call__
    await route(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 207, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 40, in app
    response = await func(request)
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 111, in app
    raw_response = await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.7/site-packages/starlette/concurrency.py", line 25, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/lib64/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "serve.py", line 226, in histogram
    begin = db[label]['meta']['intervalDomain'][0]
  File "/usr/local/lib/python3.7/site-packages/diskcache/persistent.py", line 774, in __getitem__
    return self._cache[key]
  File "/usr/local/lib/python3.7/site-packages/diskcache/core.py", line 1262, in __getitem__
    raise KeyError(key)
KeyError: 'intervalDomain'
```

**Comment by stevenrbrandt** [comment]
The problem seems to be parsing these 2 lines:
```
METRIC
                     7          14065405303  Metric: 3, 1 Value: ("PAPI_TOT_INS" <3>; DOUBLE; 18991718160.000000)
```
serve.py expects these to be on a single line.

This edit, which makes "METRIC" optional and ignores a line with METRIC by itself gets the system to work:
```
diff --git a/data_store/_otf2Functions.py b/data_store/_otf2Functions.py
index 26cb208..d64972b 100755
--- a/data_store/_otf2Functions.py
+++ b/data_store/_otf2Functions.py
@@ -1,5 +1,6 @@
 import os
 import re
+import sys
 import diskcache #pylint: disable=import-error
 from blist import sortedlist #pylint: disable=import-error
 from intervaltree import Interval, IntervalTree #pylint: disable=import-error
@@ -15,7 +16,7 @@ addAttrLineParser = re.compile(r'^\s+ADDITIONAL ATTRIBUTES: (.*)$')
 addAttrSplitter = re.compile(r'\), \(')
 addAttrParser = re.compile(r'\(?"([^"]*)" <\d+>; [^;]*; ([^\)]*)')

-metricLineParser = re.compile(r'^METRIC\s+(\d+)\s+(\d+)\s+Metric:[\s\d,]+Value: \("([^"]*)" <\d+>; [^;]*; ([^\)]*)')
+metricLineParser = re.compile(r'^(?:METRIC|)\s+(\d+)\s+(\d+)\s+Metric:[\s\d,]+Value: \("([^"]*)" <\d+>; [^;]*; ([^\)]*)')
 memInfoMetricParser = re.compile(r'^METRIC\s+(\d+)\s+(\d+)\s+Metric:[\s\d,]+Value: \("meminfo:([^"]*)" <\d+>; [^;]*; ([^\)]*)')

 def processEvent(self, label, event, eventId):
@@ -132,7 +133,7 @@ async def processOtf2(self, label, file, storeEvents=False, log=logToConsole):
             attrs = eventLineMatch.group(4)
             for attrMatch in re.finditer(attrParsers[currentEvent['Event']], attrs):
                 currentEvent[attrMatch.group(1)] = attrMatch.group(2)
-        else:
+        elif addAttrLineMatch is not None:
             # This line contains additional event attributes
             if currentEvent is None or addAttrLineMatch is None:
                 print(currentEvent)
@@ -144,6 +145,8 @@ async def processOtf2(self, label, file, storeEvents=False, log=logToConsole):
                 attr = addAttrParser.match(attrStr)
                 assert attr is not None
                 currentEvent[attr.group(1)] = attr.group(2) #pylint: disable=unsupported-assignment-operation
+        else:
+            print("LINE:",line,file=sys.stderr)
     # The last event will never have had a chance to be processed:
     if currentEvent is not None:
         counts = self.processEvent(label, currentEvent, str(numEvents))

```
but it may not be the right thing in the long term.

**Comment by alex-r-bigelow** [comment]
Thanks for debugging this Steve; ignoring that assertion makes sense for now, but @sayefsakin, should probably weigh in on the best way forward.

I'll look at this more closely tomorrow morning (in the middle of a meeting right now).

**Comment by sayefsakin** [comment]
This is really helpful Steve.
The `metricLineParser` regex should be able to parse multiline string. The main thing is that, while reading the trace file, both serve and bundle are explicitly splitting the stream with newline https://github.com/hdc-arizona/traveler-integrated/blob/f1ad169642e94b8d120ebf15487ff1245bb3f1e4/serve.py#L159

I guess, we have to keep reading lines until a match is found.

**Comment by alex-r-bigelow** [comment]
@stevenrbrandt Sorry to keep asking for things; I can't seem to get JetLag to reproduce an OTF2 trace with these newlines; would it be possible for you to send a zip of your `OTF2_archive` directory from that job so that we can make sure that a patch actually fixes this?

**Comment by stevenrbrandt** [comment]
@alex-r-bigelow I can. It seems to be even worse... even with my hack, sometimes there are unexpected newlines in other places:
```
Parse line: METRIC                                     3          13627979487  Metric: 1, 1 Value: ("PAPI_TOT_CYC" <1>; DOUBLE; 11573389074.000000)
Parse line: METRIC                                     3          13627979487  Metric: 2, 1 Value: ("PAPI_BR_MSP" <2>; DOUBLE; 8816930.000000)
Parse line: METRIC                                     3          13627979487  Metric: 3, 1 Value: ("PAPI_TOT_INS" <3>; DOUBLE; 21349870554.000000)
Parse line: METRIC                                     3          13627979487  Metric: 4, 1 Value: ("PAPI_BR_INS" <4>; DOUBLE; 4140981562.000000)
Parse line: METRIC                                     3          13627979487  Metric: 5, 1 Value: ("PAPI_LD_INS" <5>; DOUBLE; 8029975132.000000)
Parse line: METRIC                                     3          13627979487  Metric: 6, 1 Value: ("PAPI_SR_INS" <6>; DOUBLE;
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 370, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 133, in __call__
```

**Comment by stevenrbrandt** [comment]
@alex-r-bigelow I wonder if this could be an otf2-print version issue? I have 2.2.

**Comment by stevenrbrandt** [comment]
@alex-r-bigelow  Wait... you're using the same jetlag container I am, aren't you?

**Comment by sayefsakin** [comment]
I just realized that I have been trying to reproduce this in different way. I tried with `bundle.py` first and provided the trace file with `--otf2` argument. It bundled perfectly with no error.

When I run `serve.py` first and then provide the trace file from the UI by clicking `upload performance data` button, then it crashed with the following logs

```
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/home/sayefsakin/.local/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 370, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sayefsakin/.local/lib/python3.6/site-packages/starlette/applications.py", line 133, in __call__
    await self.error_middleware(scope, receive, send)
  File "/home/sayefsakin/.local/lib/python3.6/site-packages/starlette/middleware/errors.py", line 122, in __call__
    raise exc from None
  File "/home/sayefsakin/.local/lib/python3.6/site-packages/starlette/middleware/errors.py", line 100, in __call__
    await self.app(scope, receive, _send)
  File "/home/sayefsakin/.local/lib/python3.6/site-packages/starlette/exceptions.py", line 73, in __call__
    raise exc from None
  File "/home/sayefsakin/.local/lib/python3.6/site-packages/starlette/exceptions.py", line 62, in __call__
    await self.app(scope, receive, sender)
  File "/home/sayefsakin/.local/lib/python3.6/site-packages/starlette/routing.py", line 585, in __call__
    await route(scope, receive, send)
  File "/home/sayefsakin/.local/lib/python3.6/site-packages/starlette/routing.py", line 207, in __call__
    await self.app(scope, receive, send)
  File "/home/sayefsakin/.local/lib/python3.6/site-packages/starlette/routing.py", line 43, in app
    await response(scope, receive, send)
  File "/home/sayefsakin/.local/lib/python3.6/site-packages/starlette/responses.py", line 197, in __call__
    async for chunk in self.body_iterator:
  File "/mnt/c/Users/sayef/IdeaProjects/traveler-integrated/data_store/loggers.py", line 17, in iterate
    await startProcess()
  File "./serve.py", line 208, in startProcess
    await db.processOtf2(label, FakeOtf2File(request), storeEvents, logger.log)
  File "/mnt/c/Users/sayef/IdeaProjects/traveler-integrated/data_store/_otf2Functions.py", line 78, in processOtf2
    async for line in file:
  File "./serve.py", line 196, in __aiter__
    for line in chunk.decode().split('\n'):
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 189: invalid start byte
INFO: ('127.0.0.1', 50203) - "GET /datasets HTTP/1.1" 200
INFO: ('127.0.0.1', 50203) - "GET /datasets/sdfds HTTP/1.1" 200
INFO: ('127.0.0.1', 50205) - "GET /static/img/trash.svg HTTP/1.1" 200
INFO: ('127.0.0.1', 50206) - "GET /static/img/colors.svg HTTP/1.1" 200
INFO: ('127.0.0.1', 50207) - "GET /static/img/assemble.svg HTTP/1.1" 200
INFO: ('127.0.0.1', 50203) - "GET /datasets/sdfds/primitives HTTP/1.1" 200
INFO: ('127.0.0.1', 50208) - "GET /static/img/warning.svg HTTP/1.1" 404
INFO: ('127.0.0.1', 50208) - "GET /datasets/sdfds/histogram HTTP/1.1" 500
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/home/sayefsakin/.local/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 370, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sayefsakin/.local/lib/python3.6/site-packages/starlette/applications.py", line 133, in __call__
    await self.error_middleware(scope, receive, send)
  File "/home/sayefsakin/.local/lib/python3.6/site-packages/starlette/middleware/errors.py", line 122, in __call__
    raise exc from None
  File "/home/sayefsakin/.local/lib/python3.6/site-packages/starlette/middleware/errors.py", line 100, in __call__
    await self.app(scope, receive, _send)
  File "/home/sayefsakin/.local/lib/python3.6/site-packages/starlette/exceptions.py", line 73, in __call__
    raise exc from None
  File "/home/sayefsakin/.local/lib/python3.6/site-packages/starlette/exceptions.py", line 62, in __call__
    await self.app(scope, receive, sender)
  File "/home/sayefsakin/.local/lib/python3.6/site-packages/starlette/routing.py", line 585, in __call__
    await route(scope, receive, send)
  File "/home/sayefsakin/.local/lib/python3.6/site-packages/starlette/routing.py", line 207, in __call__
    await self.app(scope, receive, send)
  File "/home/sayefsakin/.local/lib/python3.6/site-packages/starlette/routing.py", line 40, in app
    response = await func(request)
  File "/home/sayefsakin/.local/lib/python3.6/site-packages/fastapi/routing.py", line 111, in app
    raw_response = await run_in_threadpool(dependant.call, **values)
  File "/home/sayefsakin/.local/lib/python3.6/site-packages/starlette/concurrency.py", line 25, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./serve.py", line 282, in histogram
    begin = db[label]['meta']['intervalDomain'][0]
  File "/home/sayefsakin/.local/lib/python3.6/site-packages/diskcache/persistent.py", line 774, in __getitem__
    return self._cache[key]
  File "/home/sayefsakin/.local/lib/python3.6/site-packages/diskcache/core.py", line 1262, in __getitem__
    raise KeyError(key)
KeyError: 'intervalDomain'
```

This error occurs with any trace file, if I try to upload it from the UI. I did some digging of this problem and found that, `bundle.py` and `serve.py` use totally different approach to reading trace files.  `bundle.py` sends the trace file with `otf2-print` subprocess as follows:

https://github.com/hdc-arizona/traveler-integrated/blob/e4110e12591d79e810ab29a1a65a4a2e4ef9c691/bundle.py#L38

But `serve.py` tries to read it directly from the input stream (without running it through `otf2-print`):

https://github.com/hdc-arizona/traveler-integrated/blob/e4110e12591d79e810ab29a1a65a4a2e4ef9c691/serve.py#L158

So any other script calling the following API technically should fail. 

https://github.com/hdc-arizona/traveler-integrated/blob/e4110e12591d79e810ab29a1a65a4a2e4ef9c691/serve.py#L162

I am not sure if @stevenrbrandt is facing the problem in this exact same way (atleast I got a different crash log than Steve). Could you please share how you are running the traveler and reading the trace file?

**Comment by alex-r-bigelow** [comment]
Oh shoot, you're totally right that it's probably something like a broken pipe on the JetLag side? This is the code that pipes otf2-print lines to the running serve.py instance: https://github.com/STEllAR-GROUP/JetLag/blob/704038d11ac6dc41205b6bc477bc1ae8ba2299e9/visualizeInTraveler.py#L55

**Comment by stevenrbrandt** [comment]
Hey, just catching up. My inbox got overwhelmed during the week. This looks promising.

**Comment by alex-r-bigelow** [comment]
@stevenrbrandt, sorry for the delay. I've finally got everything set back up, and tried again to replicate this, but now I can't even get JetLag to behave (running from current `master`). It looks like it's not bringing any OTF2 back when I run `remote_test.py` anymore (see this branch to replicate: https://github.com/alex-r-bigelow/JetLag/tree/debugging-missing-otf2)

Also, attempting to run things in Jupyter gives me this error:

<details><summary>Click to expand</summary>
<pre>
fib(17)=...
Job ID: d24560ab-60b0-425e-a752-60a69cf833dd-007
Cleanup: rostam-sbrandt-storage-tg457049/tjob/abigelow/py-fun-0111549476...done
SUBMITTING
RUNNING
Cleanup: rostam-sbrandt-storage-tg457049/tjob/abigelow/py-fun-0363417974...done
FINISHED

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-2-c19cd44f0e1f> in <module>
     10 job = remote_run(uv, fib, (fibno,), nodes=1, ppn=1)
     11 job.wait()
---> 12 print("result:",job.get_result())
     13 
     14 try:

/JetLag/jetlag.py in get_result(self)
    285                 for out in outs:
    286                     if re.match(r'.*(\.(out|err))$',out):
--> 287                         self.uv.get_file(self.jobid, out, jobdir+"/"+re.sub(r'.*\.','job.',out))
    288             if os.path.exists(jobdir+'/run_dir/result.py'):
    289               with open(jobdir+'/run_dir/result.py',"r") as fd:

/JetLag/jetlag.py in get_file(self, jobid, fname, as_file)
   1735         pause()
   1736         response = requests.get(self.fill("{apiurl}/jobs/v2/")+jobid+"/outputs/media/"+fname, headers=headers)
-> 1737         check(response)
   1738         content = response.content
   1739         is_binary = False

/JetLag/jetlag.py in check(response)
    151     an error was not received.
    152     """
--> 153     assert response.status_code in success_codes, str(response)+response.content.decode()
    154 
    155 def idstr(val,max_val):

AssertionError: <Response [500]><am:fault xmlns:am="http://wso2.org/apimanager"><am:code>101504</am:code><am:type>Status report</am:type><am:message>Runtime Error</am:message><am:description>Send timeout</am:description></am:fault>

</pre>
</details>

**Comment by stevenrbrandt** [comment]
@alex-r-bigelow you are seeing a transient error from Tapis at TACC. Not sure why that happens at the moment. Add this code to your notebook, and you should be able to get the job:
```
# The big string is your job ID which I copied from your error message
job = RemoteJobWatcher(uv, "d24560ab-60b0-425e-a752-60a69cf833dd-007")
print(job.get_result())
viz(job)
```

**Comment by stevenrbrandt** [comment]
any updates?

**Comment by alex-r-bigelow** [comment]
Just tested again this morning; `remote_test.py` still doesn't get any OTF2 data to put into traveler (did this move from `job-***/run_dir`?)

Also just discovered that an update broke my docker setup on Windows (again!), so I'll report back about jupyter as soon as that's fixed.

**Comment by alex-r-bigelow** [comment]
Okay, I think I've finally been able to replicate it from Jupyter, and it's definitely an issue on the JetLag side somehow adding what seem to be random newlines into the piped OTF2 trace.

This is really hard for me to debug inside `docker-compose` on Windows (tbh, I still barely feel competent poking around inside a single running docker container), so I'm going to try to set up + run JetLag without it, and hopefully replicate it independently (also totally possible that it's something wrong in the docker setup). @stevenrbrandt, you're probably better equipped to debug this than I am—so if you need a quick fix, waiting on me to figure it out isn't a great idea.

**Comment by stevenrbrandt** [comment]
@alex-r-bigelow you can always `docker exec -it --user 0 trav bash` and get a root command line in the image where you can edit the traveler files, etc. directly. I know you're not fond of chatting, but I'm on Skype if that helps.

**Comment by stevenrbrandt** [comment]
@alex-r-bigelow @sayefsakin any updates?

**Comment by stevenrbrandt** [comment]
This morning I finally found what was wrong. The __aiter__ method in FakeOtf2File assumes that it gets a new line. This code fixes the problem:
```
diff --git a/serve.py b/serve.py
index 8a472b6..142cc55 100755
--- a/serve.py
+++ b/serve.py
@@ -155,10 +155,17 @@ class FakeOtf2File: #pylint: disable=R0903
         self.name = 'APEX.otf2'
         self.request = request
     async def __aiter__(self):
+        line = ''
         async for chunk in self.request.stream():
-            for line in chunk.decode().split('\n'):
-                if line != '':
-                    yield line
+            line += chunk.decode()
+            done = False
+            while not done:
+                done = True
+                i = line.find('\n')
+                if i >= 0:
+                    yield line[0:i]
+                    line = line[i+1:]
+                    done = False
 @app.post('/datasets/{label}/otf2')
```
